window:
  opacity: 0.8

font:
  normal:
    family: iosevka nerd font
    style: Regular

items:
  - colors:
      name: Isotope (dark)
      author: Chris Kempson
      primary:
        background: "#000000"
        foreground: "#d0d0d0"
      cursor:
        text: "#000000"
        cursor: "#d0d0d0"
      normal:
        black: "#000000"
        red: "#ff0000"
        green: "#33ff00"
        yellow: "#ff0099"
        blue: "#0066ff"
        magenta: "#cc00ff"
        cyan: "#00ffff"
        white: "#d0d0d0"
      bright:
        black: "#808080"
        red: "#ff0000"
        green: "#33ff00"
        yellow: "#ff0099"
        blue: "#0066ff"
        magenta: "#cc00ff"
        cyan: "#00ffff"
        white: "#ffffff"
  - theme: Isotope.dark
colors:
  name: Brewer (dark)
  author: Chris Kempson
  primary:
    background: "#0c0d0e"
    foreground: "#b7b8b9"
  cursor:
    text: "#0c0d0e"
    cursor: "#b7b8b9"
  normal:
    black: "#0c0d0e"
    red: "#e31a1c"
    green: "#31a354"
    yellow: "#dca060"
    blue: "#3182bd"
    magenta: "#756bb1"
    cyan: "#80b1d3"
    white: "#b7b8b9"
  bright:
    black: "#737475"
    red: "#e31a1c"
    green: "#31a354"
    yellow: "#dca060"
    blue: "#3182bd"
    magenta: "#756bb1"
    cyan: "#80b1d3"
    white: "#fcfdfe"
theme: Brewer.dark
