#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off

bspc config border_width         0
bspc config window_gap           10
bspc config top_padding          20
bspc config bottom_padding       0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width         2
bspc config focused_border_color "#121218"
bspc config normal_border_color  "#282e3a"

nitrogen --restore &
picom &

bash ~/.config/polybar/newdark/launch.sh

xfce4-power-manager
sxhkd
#/usr/lib/xfce-polkit/xfce-polkit
